### PR TITLE
LPS-71378 Update context for nested fields

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 Hope this to be the last one :)

**Comment by vicnate5** [comment]
🤞

**Comment by vicnate5** [comment]
Progress. Now the data provider is missing from the selector.

progress

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 It seems it's working!

**Comment by vicnate5** [comment]
bobokntlr8rti

**Comment by leoadb** [comment]
Kkkkkkkkkkkkk

**Comment by marcellustavares** [comment]
easier than we thought 😆

**Pull request closed without merging**
