### PR TITLE
LPS-111537 Fix portal-reports-engine-console dependencies

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @leoadb @yxingwu

This PR updates POI versions across the portal. @leoadb some DDM/DDL tests are failing (looks like regular failures, not related to these changes), so we need to fix them before forwarding.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/797

**Pull request closed without merging**
