### PR TITLE
LPS-71378 REMOVE

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by vicnate5** [comment]
This a run we expect to pass? User cannot save a form.

**Comment by leoadb** [comment]
Weird!

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
Still some issues with save and display a form

saveform
formpage

**Comment by leoadb** [comment]
Yeah

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
@leoadb Only one test failure. Something with saving a data provider configuration.

You can ignore the SF error due to `test.batch` properties. That is a subrepo thing.

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 Let's cross fingers :)

**Comment by vicnate5** [comment]
Might be worth checking this manually? Add second output when creating a data provider > Save

dataprovider

**Comment by leoadb** [comment]
Yeah ... Already did that ... I got the error ... trying to fix

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Pull request closed without merging**
