### PR TITLE
LPS-75226 Destroy dialog on hide

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Hey @vicnate5, are those real test failures or flukes? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz94 Test failures are not related to this pull.

**Comment by pedroqueiroz94** [comment]
Thanks, @vicnate5 :)

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52727. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
