### PR TITLE
LPS-113771 Handle DDL fields empty validations format during the upgrade

### PR DESCRIPTION
**Pull request by achaparro**
Added a missed commit from previous pull:
https://github.com/leoadb/liferay-portal/pull/928

@samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/937

**Pull request closed without merging**
