### PR TITLE
LPS-70000 Add tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46536. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
