### PR TITLE
LPS-70017 Update project dependencies

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
c:reopen

**Comment by rafaprax** [comment]
ci:reopen

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46017. [See changes here.](https://github.com/leoadb/liferay-portal/compare/d305925~1...d305925) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
