### PR TITLE
LPS-66472 LPS-67562 DDM: Fix Eclipse compile errors - DDM uses Java 8 API now

### PR DESCRIPTION
**Pull request by arboliveira**
https://github.com/liferay/liferay-portal/blob/02c9970e1c6cf3b0eb5dcb99ebe32625024ea67c/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-expression/src/main/java/com/liferay/dynamic/data/mapping/expression/internal/DDMExpressionFactoryImpl.java#L107-L108

https://github.com/liferay/liferay-portal/blob/02c9970e1c6cf3b0eb5dcb99ebe32625024ea67c/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-evaluator-impl/src/main/java/com/liferay/dynamic/data/mapping/form/evaluator/impl/internal/functions/CallFunction.java#L268-L271

😃

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Hi Léo! This is a small changeset (just 4 lines) but it would greatly help us with running Search related tests that depend on DDM - these will make Eclipse compile again. Do you think you could take a quick look? Thanks! 😃

**Comment by leoadb** [comment]
@arboliveira Sure !!! First thing I'll do on next monday. I was attending some courses during the whole week.

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/251. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/252. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
