### PR TITLE
[TECHNICAL-SUPPORT] LPS-76178 Portlet display templates changes are not updated [1/2]

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-76178

**First pull:** we are modifying DDMTemplateManager interface in order to be able to add a new method in DDMTemplateManagerImpl implementation 

**See second pull in:** https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/531

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
hey @jorgediaz-lr , please, check my comment in https://issues.liferay.com/browse/LPS-76178?focusedCommentId=1210472&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1210472 . Thank you!

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
