### PR TITLE
LPS-110622 remove possible garbage for previous tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:forward

**Comment by jpince** [comment]
@yichenroy webhook didn't start tests here either
worked fine in previous pulls. example: https://github.com/leoadb/liferay-portal/pull/753#issuecomment-604077697

**Comment by yichenroy** [comment]
ci:forward

**Comment by yichenroy** [comment]
@jpince Looks like the ongoing network outages might have caused unresponsive webhook sometimes, IT is working on stabilizing the network.

**Pull request closed without merging**
