### PR TITLE
J cords lps 104222 2

### PR DESCRIPTION
**Pull request by joshuacords**
Hello @leoadb,

You originally reviewed [LPS-104222](https://issues.liferay.com/browse/LPS-104222) here: https://github.com/leoadb/liferay-portal/pull/617

**Problem:**
In testing this issue I was using js_fast_load=0 in the url, however removing that parameter allows the issue to continue to be reproduced. The change of the js_fast_load status can rearrange the listeners of the form submission. 
With js_fast_load=0 the submit process calls in this order [_onFormSubmit (JournalPortlet.es.js)](https://github.com/liferay/liferay-portal/blob/8584ef70ce15cf601467107a731291aefdef21fe/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/JournalPortlet.es.js#L103-L111) and later [_onSubmitForm (ddm_form.js)](https://github.com/liferay/liferay-portal/blob/1b31e1f567ac1856223235f1dbcc8b83babd05a0/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L3933-L3943). Importantly, _onFormSubmit calls:
[_onLiferaySubmitForm](https://github.com/liferay/liferay-portal/blob/1b31e1f567ac1856223235f1dbcc8b83babd05a0/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L3923-L3931) -> [updateDDMFormInputValue](https://github.com/liferay/liferay-portal/blob/1b31e1f567ac1856223235f1dbcc8b83babd05a0/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L4312-L4318) ->[ toJSON (form)](https://github.com/liferay/liferay-portal/blob/1b31e1f567ac1856223235f1dbcc8b83babd05a0/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L4287-L4306) -> [toJSON (fields)](https://github.com/liferay/liferay-portal/blob/7a030266fb91cc18c3b535db4cb20061cad57905/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L1043-L1079) which sets the availableLanguageIds based on the localizationMap of each field. My addition of [fillEmptyLocales](https://github.com/liferay/liferay-portal/blob/1b31e1f567ac1856223235f1dbcc8b83babd05a0/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L4058-L4063) relies on the availableLanguageIds being properly set, which they are in this scenario.
However, with js_fast_load on as usual, [_onSubmitForm (ddm_form.js)](https://github.com/liferay/liferay-portal/blob/1b31e1f567ac1856223235f1dbcc8b83babd05a0/modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L3933-L3943) is called first in which case the availableLanguageIds are not yet set to any new locales which results in the pre-fix problematic behavior.

**Solution:**
This solution uses the toJSON method to trigger each field updating the availableLanguageIds. It's unfortunate that we need to run through the toJSON method before fillEmptyLocales to prepare the availableLanguageIds and then afterwards inside of updateDDMFormInputValue to save those new values in the JSON, however it seems like the simplest fix. 

If you have a better direction, let me know.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/81062

**Pull request closed without merging**
