### PR TITLE
[TECHNICAL SUPPORT] LPS-105662 Make sure to update the validation expression as well

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-105662

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brunobasto/liferay-portal/pull/1103

**Pull request closed without merging**
