### PR TITLE
[TECHNICAL SUPPORT] LPS-102947 Include resourceClassNameId to DDMStructure document so ResourcePermissions can be found under composite names

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-102947

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Those failures do not seem to be related to the pull.

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79621. [See changes here.](https://github.com/leoadb/liferay-portal/compare/da8e49f920f7~1...da8e49f920f7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
