### PR TITLE
LPS-100862 checking if host is listed by property nonProxyHosts

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77819. [See changes here.](https://github.com/leoadb/liferay-portal/compare/6eb231020bb6~1...6eb231020bb6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
