### PR TITLE
LPS-93317 Adapt generated CRUD tests for data layout

### PR DESCRIPTION
**Pull request by mclomello**
@leoadb could u review this pr please?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72571. [See changes here.](https://github.com/leoadb/liferay-portal/compare/1f9a88671853~2...1f9a88671853) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72572. [See changes here.](https://github.com/leoadb/liferay-portal/compare/ef678b0e7aac~1...ef678b0e7aac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
