### PR TITLE
LPS-113755 If we are importing to a Staging Site, the groupId should be of that Site

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @leoadb 

Not sure if you maintain DDM too, so feel free to forward this to the right person :-)

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/863

**Pull request closed without merging**
