### PR TITLE
[TECHNICAL SUPPORT] LPS-111448 Do not skip transient fields

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-111448

/cc @achaparro: I sent this pull request directly to Leonardo because I figured it wasn't necessary to add a new upgrade process before the `UpgradeDynamicDataMapping`. I could just make the adjustments on that and prevent it from creating invalid fields. With that, we not only avoid bringing down the upgrade's performance by adding new queries but we also improve the `UpgradeDynamicDataMapping`'s performance by not having to serialize the fields that are not good.

Please let me know in case both of you have any questions related to this.

PS.: @leoadb, for better understanding of the approach taken in this PR, please refer to the **PTR** in the related LPP.

Best.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:forms

**Comment by rodrigopaulino** [comment]
ci:test:app-builder

**Comment by leoadb** [comment]
@rodrigopaulino Can you please check the errors? Thanks!

**Comment by rodrigopaulino** [comment]
@leoadb I believe these errors were already happening before.

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:test:app-builder

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/812

**Pull request closed without merging**
