### PR TITLE
Lps 102733

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:
> https://issues.liferay.com/browse/LPS-102733
> Previous pr: https://github.com/leoadb/liferay-portal/pull/570
> 
> Edited the test to check for 4 digit year instead of 2 digit year and changed the logic for `_format` to replace the years in the date format's pattern.
> 
> The issue is the display of DDL date is not consistent. The data list stores the information with pattern `yyyy`, but on retrieve the API extracts the value with pattern `yy`. The solution is to use a different function that uses the specified date pattern intended to keep consistency.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/578. [See changes here.](https://github.com/leoadb/liferay-portal/compare/2110ec35c415~1...2110ec35c415) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79552. [See changes here.](https://github.com/leoadb/liferay-portal/compare/fb696c5e3b00~1...fb696c5e3b00) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
