### PR TITLE
LPS-89907 Add integration tests

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68245. [See changes here.](https://github.com/leoadb/liferay-portal/compare/b4465509af70~1...b4465509af70) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/68295. [See changes here.](https://github.com/leoadb/liferay-portal/compare/293214eb67f1~2...293214eb67f1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
