### PR TITLE
Lps 102450 master

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-102450

During the UpgradeDDMFormInstanceRecordVersion process if a value in the DDMStorageId column from the DDLRecordVersion table is larger than 2,147,483,647 the upgrade will fail. The reason for this is we are using rs.getInt rather than rs.getLong during the upgrade to grab the value.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:upgrade

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/79069

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
