### PR TITLE
LPS-55879

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/31006

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/78. [See changes here.](https://github.com/leoadb/liferay-portal/compare/63bb127~1...63bb127) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/88. [See changes here.](https://github.com/leoadb/liferay-portal/compare/ba4257d~4...ba4257d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
