### PR TITLE
LPS-103222 search in all available locales

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/588. [See changes here.](https://github.com/leoadb/liferay-portal/compare/02d07ceb5fca~1...02d07ceb5fca) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
