### PR TITLE
LPS-103222 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@linolaoj It seems there are real errors here. Can you please take a look? Thanks!

**Comment by linolaoj** [comment]
Hi @leoadb, tests from DDLExporterTest are failing on current upstream master.

**Comment by leoadb** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/79651. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
