### PR TITLE
LPS-69587 SF Soy compiled

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46011. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
