### PR TITLE
LPS-57100 Regenerate

### PR DESCRIPTION
**Pull request by marcellustavares**
@leoadb, I think build will fail b/c of the jsps, could you please continue the DL jsps layer?

Let's go with your strategy :) and clean up everything during this week.

There will be just a few references left after this pull but I already know what they are. will fix them tomorrow.

Thanks a lot!

### CODE REVIEW

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Hey @marcellustavares , do you mean change references of all DDM model classes or just DDMStructure ? :)

**Comment by marcellustavares** [comment]
just DDMStructure for this pull :)

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/24. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/639. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
