### PR TITLE
LPS-75936

### PR DESCRIPTION
**Pull request by topolik**
Hi Leonardo,

can you please peer review this code?

The problem is that FullPageApplication LayoutType and SharedPortlet layout type inherits from `ModificationDeniedLayoutTypeAccessPolicyImpl` that is insecure by default. Returns "true" for security checks. Also it actually doesn't prevent modification of the layout, still changes can be done.

@JorgeFerrer provided fix for FPA LayoutType. 

The idea of SharedPortlet is unlucky, because we can't display portlets as we wish. So I moved the logic inside DDLFormPortlet module and deprecated/removed whole SharedPortlet LayoutType.

I mostly only refactored the code so it should work, I didn't encounter new any errors during my testing.

But please can you double check? If it's fine please send it to Brian Chan.

Thank you!

/cc @istvansajtos @lipusz

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
@leoadb Please give a high priority to this fix due to its nature. Details are on the LPS.

Thanks!

**Comment by topolik** [comment]
Hi @leoadb,

when you send the PR to Brian, please ask him to not backport it to 7.0.x branch, we need QA to test it in master first.

Thanks.

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/pedroqueiroz94/liferay-portal/pull/40. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
