### PR TITLE
LPS-99844 Auto SF - dependencies versions

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
@leoadb SF and test errors caused by rebase verification - this pull is rebased with brianchandotcom/master which hasn't been synchronized yet.

Hey @jbalsas, could you please take a look at https://github.com/leoadb/liferay-portal/pull/700/commits/a98d8262eb2b42e150d805c27551c826038714e9?
It seems that we have to extract FieldBase and related common stuff to a separate module to avoid build errors in the future.

/cc @ealonso

**Comment by ealonso** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Hey @pavel-savinov, this is a build issue and should be addressed in build tooling.

/cc @izaera, @wincent, could you guys take a look here? I think this fails because our `imports` config for the `npmbunlderrc` does not solve transitive dependencies. Thus, when we import a module that has configured `imports` we try to process them instead of skipping it. (this is just my early assessment though, so it might be something else).

I think we likely want to add an auto-link feature for those modules that are not `preset-standard` or something like that, so we auto-import all modules inside the yarn workspace automatically. This would also cleanup most of our `.npmbundlerrc` config files in `liferay-portal`.

**Comment by wincent** [comment]
I added https://issues.liferay.com/browse/IFI-1451 to track the proposed changes (unassigned at this point but I expect it will be @izaera who does all of the Bundler v3 work).

**Comment by pavel-savinov** [comment]
@leoadb Rebased with latest liferay/liferay-portal master.

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/84926

**Pull request closed without merging**
