### PR TITLE
LPS-114001 partial revert of LPS-105572 commit 58377c91742faebb76ab540f3ea24e4235b6bda1 Do not use the current value as placeholder value when creating a new locale

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
ci:forward

**Comment by NemethNorbert** [comment]
I made an additional commit, please find
https://github.com/liferay/liferay-portal/pull/3839

**Comment by NemethNorbert** [comment]
I made an additional commit, please find:
https://github.com/leoadb/liferay-portal/pull/882

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/882

**Pull request closed without merging**
