### PR TITLE
LPS-75217 Refactoring and fix condition that may not catch choice update if one choice is removed and a new one created. Size of lists would be equals.

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
Retesting before forward to BChan.

**Comment by leoadb** [comment]
@jonathanmccann Can you please manually retest my changes to check if is still working? Thanks!

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@leoadb It appears that it is working.

**Pull request closed without merging**
