### PR TITLE
LPS-116284 Add nested fields to fields

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @leoadb ,
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
Thank you @rolandpakai for your help:)

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/933

**Pull request closed without merging**
