### PR TITLE
[TECHNICAL SUPPORT] LPS-105752 Fields can have more than one value if it is repeatable

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-105752

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/640

**Pull request closed without merging**
