### PR TITLE
master-vw-160

### PR DESCRIPTION
**Pull request by vicnate5**
Hey Leonardo, I was able to fix the poshi test for this update but the test is going to fail due to a bug. There is no success message when saving the new file. I also noticed that the uploader is not showing the progress bar correctly. Can you take another look at this before sending it in?

Thanks!

CC @marcellustavares @brunobasto

### CODE REVIEW

**Comment by vicnate5** [comment]
gif of the current behavior
https://www.dropbox.com/s/zythx09516k0t70/WorkflowUploadIssues.gif?dl=0

**Comment by leoadb** [comment]
@vicnate5 Thanks for your help !!! I'll take a look on that again.

**Comment by marcellustavares** [comment]
Thanks for the help @vicnate5

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/171. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/165. [See changes here.](https://github.com/leoadb/liferay-portal/compare/c3f667b~1...c3f667b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
