### PR TITLE
LPS-95080 getting pages from context to get field options

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/1031. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
