### PR TITLE
LPS-101288 baseline

### PR DESCRIPTION
**Pull request by linolaoj**
Hi @leoadb , 
In this pull I'm also applying the fix to xls format. I did not include part of your SF 1ca7f7c5077c8856ce782ba8759184749bbd4fca because it was not printing correctly when the record had some empty field value.
Thanks!

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Hi @inacionery , 
I've talked with @natocesarrego, and I'm going to resend with the new behavior suggested.
Thanks!

**Comment by linolaoj** [comment]
Here it is https://github.com/leoadb/liferay-portal/pull/567

**Comment by natocesarrego** [comment]
Thanks, @linolaoj! 😉

**Pull request closed without merging**
