### PR TITLE
LPS-117692 set ddmTemplateName and ddmTemplateKey when ddmTemplate changes

### PR DESCRIPTION
**Pull request by marcosapmf**
Related issue: https://issues.liferay.com/browse/LPS-117692

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/984

**Pull request closed without merging**
