### PR TITLE
[TS] LPS-102621 dynamic-data-mapping-service: Allow for template to recover from exceptions when attempting to retrieve a fileEntry

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-102621

Hi @leoadb  ,

Can you help me review this pr?

**Context**
DDM currently utilizes a FreeMarker template that needs to fetch for a fileEntry. 

However, DLAppService does not provide an API that can fetch for a fileEntry (without throwing any exceptions).

**Issue:** This results in a situation where users are unable to recover from when only using the UI (without a workaround).

This pr introduces error handling within the FreeMarker template. Including this error handling at least allows for the template to properly render, which allows users to recover from this situation. 

**Note:** FreeMarker will still log the errors, even though the template recovers. This is expected: https://freemarker.apache.org/docs/ref_directive_attempt.html

**Note:** It's possible that a better fix may be to implement better handling on the DDL or DDM side. But, this fix would at least allow for users to recover from this situation for now.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/79237

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
