### PR TITLE
LPS-59347 Create actionURL to use in form action

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
I re-started this job on 10/15/15 at 12:12pm

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31273. [See changes here.](https://github.com/leoadb/liferay-portal/compare/2500366~1...2500366) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31274. [See changes here.](https://github.com/leoadb/liferay-portal/compare/d310cf8~1...d310cf8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
