### PR TITLE
LPS-93142 Add data definition with field and validation.

### PR DESCRIPTION
**Pull request by mclomello**
@leoadb

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73520. [See changes here.](https://github.com/leoadb/liferay-portal/compare/c5b013500335~1...c5b013500335) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
