### PR TITLE
LPS-111537 Fix portal-reports-engine-console dependencies

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
@marcelabc can you help me with this? We need to fix some tests. Thanks!

**Comment by marcelabc** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
