### PR TITLE
LPS-60963 Fix layout validation error

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Que beleza!

**Comment by leoadb** [comment]
Uuuhhhhhh :)

Em sex, 11 de dez de 2015 18:41, Marcellus Tavares <notifications@github.com>
escreveu:

**Comment by leoadb** [comment]
@marcellustavares are you going to send to Brian or there is something missing ?

**Comment by marcellustavares** [comment]
I've just did, https://github.com/brianchandotcom/liferay-portal/pull/33263

Thx @leoadb

**Pull request closed without merging**
