### PR TITLE
LPS-102733 Change default date format to use pattern that displays 4 …

### PR DESCRIPTION
**Pull request by inacionery**
/cc @knchau

Notes from Kim:

> https://issues.liferay.com/browse/LPS-102733
> 
> The issue is the display of DDL date is not consistent. The data list stores the information with pattern `"yyyy"`, but on retrieve the API extracts the value with pattern `"yy"`. The solution is to use a different function that uses the specified date pattern intended to keep consistency.

### CODE REVIEW

**Comment by inacionery** [comment]
Hey @knchau,

I don't think this is the right solution, because you're changing a utility class from the Kernel to meet a DDL requirement.

Thanks!

**Comment by knchau** [comment]
Hi @inacionery,

I see, I'll go back and look into it!

**Comment by knchau** [comment]
Updated pr: https://github.com/SamZiemer/liferay-portal/pull/662

**Pull request closed without merging**
