### PR TITLE
Lps 102733

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:

> https://issues.liferay.com/browse/LPS-102733
> 
> The issue is the display of DDL date is not consistent. The data list stores the information with pattern `yyyy`, but on retrieve the API extracts the value with pattern `yy`. The solution is to use a different function that uses the specified date pattern intended to keep consistency.

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by knchau** [comment]
Hi @leoadb,

The test failure is due to the change from displaying 2 year digit to 4 year digit. Changing the assertion of that test would only be needed to pass the test. Please let me know if you'd like a new PR for this.

Thank you!

**Comment by knchau** [comment]
ci:close

**Pull request closed without merging**
