### PR TITLE
LPS-109882 choose only one app to save time and resources

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@alexcandidos @brunofarache please see my last commit. We need to downsize the number of apps included in test.properties. I will do the same for test.properties inside DDM and DDL. Let's talk about this. Thanks!

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@alexcandidos @brunofarache please see my last commit. We need to downsize the number of apps included in test.properties. Let's talk about this. Thanks!

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
@alexcandidos why the test **Forms#PreviewAndPublishForm**  got executed?

**Comment by alexcandidos** [comment]
Hey @leoadb , it is weird, according to your last commit changing the test.properties of some modules, if you were only touching the Data Engine module, the query of this project should have executed App Builder relevant tests only. And if you had touched something at dynamic-data-mapping module, Forms test should have been executed, plus journal relevant set.

cc: @brunofarache

**Comment by cvanut** [comment]
Hi @leoadb 
Forms#PreviewAndPublishForm is passing on ci:test:forms since the beggining of March, as you can see [here](https://testray.liferay.com/home/-/testray/case_results/1069721793/history?tab=result&hideFilterPin=true).  However, the same error you got had been reproduced twice in the last two months. Maybe it can be considered as a flaky test and needs a testfix. I'll take a look on the and then I update it here.

**Pull request closed without merging**
