### PR TITLE
LPS-104312 Use the new ItemSelectorDialog in DDM

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @leoadb , 

we are removing uses of the old AUI _liferay-item-selector-dailog_ component. I am sending this to you so you can verify if everything works as before (internal interactions inside the Item Selector has been changed a little bit but the final result must be the same). 

Thank you in advance!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
@leoadb just pushed a SF commit

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by leoadb** [comment]
@ambrinchaudhary It seems we have a regression on Forms. I've asked our QA to test on Master and it is working there. In this PR, after I select a file to upload, the file name is not being set in the input. Can you please take a look? Thanks!

**Comment by ambrinchaudhary** [comment]
New PR: https://github.com/leoadb/liferay-portal/pull/620

**Pull request closed without merging**
