### PR TITLE
LPS-104247 Accumulate nested field values

### PR DESCRIPTION
**Pull request by JavierMoral**
This pull fixes LPS-104247
It changes a class that originally belonged to WCM but was moved to DDM in LPS-96705
Could you please take a look at it?

Thanks!

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/614

**Pull request closed without merging**
