### PR TITLE
LPS-71378 Java

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@leoadb compile error?

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/333. [See changes here.](https://github.com/leoadb/liferay-portal/compare/5652402~1...5652402) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
@vicnate5 Snapshot issue. :) This is a complication to the scenario we have :(. We need subrepo to be merged first, then wait for snapshot (nexus), change gradle reference and finally send the PR to DDL :)

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/841. [See changes here.](https://github.com/leoadb/liferay-portal/compare/2aee8e7~10...2aee8e7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/334. [See changes here.](https://github.com/leoadb/liferay-portal/compare/dca70a1~10...dca70a1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
