### PR TITLE
LPS-99569 Replace the delete method for one that reindexes

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/77395. [See changes here.](https://github.com/leoadb/liferay-portal/compare/371bf8cbf704~3...371bf8cbf704) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
