### PR TITLE
LPS-99120 Disable senna in data provider form

### PR DESCRIPTION
**Pull request by mclomello**
cc @jpince

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78459. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
