### PR TITLE
LPS-71571 Add alternative poshi paths to Basic and Properties tabs

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
vi:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:reopen

**Comment by leoadb** [comment]
Pull request forwarded to https://github.com/rafaprax/liferay-portal/pull/211. [See changes here.](https://github.com/leoadb/liferay-portal/compare/5607067~1...5607067) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
