### PR TITLE
J cords lps 101662 3

### PR DESCRIPTION
**Pull request by joshuacords**
Hello @leoadb,

This is a fix for [LPS-101662](https://issues.liferay.com/browse/LPS-101662). The [original](https://github.com/arboliveira/liferay-portal/pull/769) was sent to arboliveira but the changes to the QueryHelperAPI weren't allowed. See his comments [here](https://issues.liferay.com/browse/LPS-101662?focusedCommentId=1961903&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1961903), I followed his suggestions to arrive at this fix.

**Problem:** [queryHelper.addSearchLocalizedTerm()](https://github.com/liferay/liferay-portal/blob/237b9f6bc506deb197ef82a248dd67425ab5e092/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/query/QueryHelperImpl.java#L44-L51) only considers the 1 locale in the searchContext for localizing the fieldname during the search. This results in situations where the normal results will list entries that a search will not find if the searched term is in a different language. (See ticket for more info.) 

**Solution:** Instead call [queryHelper.addSearchTerm()](https://github.com/liferay/liferay-portal/blob/237b9f6bc506deb197ef82a248dd67425ab5e092/modules/apps/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/query/QueryHelperImpl.java#L54) for each available locale from the affected QueryContributors.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
ci:test:search

**Comment by inacionery** [comment]
Forwarded to https://github.com/inacionery/liferay-portal/pull/228

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
