### PR TITLE
LPS-104599 Reorganizing the upgrade processes to be able to backport it to 7.2.x

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @rodrigopaulino

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/82812

**Pull request closed without merging**
