### PR TITLE
LPS-112731 Rename

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
@IstvanD Real errors here. Can you please fix on top of my changes and send me back? Thanks!

**Comment by leoadb** [comment]
@IstvanD I just sent to you here https://github.com/IstvanD/liferay-portal/pull/102

**Comment by IstvanD** [comment]
@leoadb had to revert the changes made in e136aee2e8fa3db332f48ee87c794991a7ac2bcf in order for the tests to pass.

**Pull request closed without merging**
