### PR TITLE
LPS-62169 Update poshi upload

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by vicnate5** [comment]
Looks like this needs an additional poshi fix for the lexicon table.

**Comment by vicnate5** [comment]
The page also does not redirect to the Workflow Definitions table on save (which was the old behavior). Now the user must click "back" to access the table. Is this an intended change?

**Comment by leoadb** [comment]
No, it's not. I'll fix that. Thanks.

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 I just fixed the redirect after saving a definition and there are still some Poshi errors. I'll forward to you. I appreciate if you take a look again. Thanks !!!

**Pull request closed without merging**
