### PR TITLE
LPS-91183 When the locale change, sync the field label

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73524. [See changes here.](https://github.com/leoadb/liferay-portal/compare/83b28957f752~1...83b28957f752) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
