### PR TITLE
LPS-71909 remove required property from fields on disable pages

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:reopen

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50007. [See changes here.](https://github.com/leoadb/liferay-portal/compare/c6ef212~1...c6ef212) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50019. [See changes here.](https://github.com/leoadb/liferay-portal/compare/897c07a~2...897c07a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
