### PR TITLE
LPS-107198 Saves journal structure using data layout builder

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:sf

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
ci:test:app-builder

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/678

**Pull request closed without merging**
