### PR TITLE
LPS-104808 checking if option still exists

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/81216

**Pull request closed without merging**
