### PR TITLE
LPS-74385 Update project dependencies

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/380. [See changes here.](https://github.com/leoadb/liferay-portal/compare/7b475fd~1...7b475fd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/854. [See changes here.](https://github.com/leoadb/liferay-portal/compare/a6816dc~3...a6816dc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/855. [See changes here.](https://github.com/leoadb/liferay-portal/compare/3dfd988~4...3dfd988) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/857. [See changes here.](https://github.com/leoadb/liferay-portal/compare/1fc8c8e~5...1fc8c8e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/vicnate5/liferay-portal/pull/858. [See changes here.](https://github.com/leoadb/liferay-portal/compare/d400eee~6...d400eee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
