### PR TITLE
LPS-109809 reverting d59435b3f4a3b76ef602b176026dc3d976dabeaa and faea363eae0da7f7c2c30673114ad31bbbcfcd2f because the order matters

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
@yichenroy no tests initiated on the first try, looks like it's going now.

**Comment by jpince** [comment]
@leoadb see https://liferay.slack.com/archives/C19PWQ74J/p1585233041043500?thread_ts=1585213374.038900&cid=C19PWQ74J for options to get around the SF issue

@rodrigocunhaa SF issue is blocking this pull as well. This pull fixes the issue that is currently blocking the stable job & merge to upstream master.

**Comment by rodrigocunhaa** [comment]
https://github.com/rodrigocunhaa/liferay-portal/pull/27

**Comment by leoadb** [comment]
@jpince I will wait for it. Thanks!

**Comment by rodrigocunhaa** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/86836

**Comment by jpince** [comment]
@leoadb is something still broken? a lot of tests failing. Can you and @alexcandidos please make this a priority? Or revert the entire ticket until we're able to come up with a better fix. Thank you!

**Comment by leoadb** [comment]
@jpince I don't even know why those tests get executed. We updated test.properties from data-engine to run only app-builder relevant. I sent this rebasing with Brian's master because they were not in master yet.

**Comment by leoadb** [comment]
@jpince My original pull was ok, I just reverted some commits Brian made during the review.

**Comment by jpince** [comment]
@leoadb sorry I don't have a good answer. @alexcandidos maybe another Test Lead or someone from CII will know why so many tests are running?

**Comment by yichenroy** [comment]
@leoadb The pull request tests run against upstream on `liferay`, so when a branch is based off of `brianchandotcom` the diff will be whatever hasn't been sync'd into `liferay` + your changes so `ci:test:relevant` detects that the branch contains changes in various parts of portal and thus running a larger pool of tests.

cc @jpince

**Comment by leoadb** [comment]
@yichenroy I see!! Thanks to let me know. I could send rebased with master because they did get in. I'm supposed that the error caused by the changes is avoiding those commits to get into master.

**Comment by leoadb** [comment]
@jpince I am afraid this is something that Brian needs to fix on his branch. Will talk to him.

**Comment by jpince** [comment]
@leoadb just send the one commit directly to BChan and ci:reopen the PR after it closes. Only for this case since it's blocking the sync to upstream.

**Comment by leoadb** [comment]
@jpince Ok, will do it. Thanks

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/86846

**Pull request closed without merging**
