### PR TITLE
LPS-62868 use ddm web configuration from request helper in case when it does not exist in request

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35533. [See changes here.](https://github.com/leoadb/liferay-portal/compare/2a74890~1...2a74890) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
