### PR TITLE
LPS-104312 Use the new ItemSelectorDialog

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
> Hey @leoadb ,
> we are removing uses of the old AUI liferay-item-selector-dailog component. I am sending this to you so you can verify if everything works as before (internal interactions inside the Item Selector has been changed a little bit but the final result must be the same).
> Thank you in advance!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/80927

**Pull request closed without merging**
