### PR TITLE
LPS-103640 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@linolaoj is this work?

**Comment by leoadb** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
Hi @leoadb ,
I could not check this yet because of LPS-103921.

**Comment by leoadb** [comment]
@linolaoj will wait then

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi @leoadb , this is working as expected.
Thanks!

**Comment by leoadb** [comment]
ci:test:revelant

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/80387

**Pull request closed without merging**
