### PR TITLE
LPS-86399 Autosave called when a new form rule is created to prevent a data provider from being deleted while being used

### PR DESCRIPTION
**Pull request by renatodepaiva**

### CODE REVIEW

**Comment by renatodepaiva** [comment]
Some tests were executed here: https://github.com/renatodepaiva/liferay-portal/pull/36

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/428. [See changes here.](https://github.com/leoadb/liferay-portal/compare/bc31b4e5ebfd~1...bc31b4e5ebfd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
