### PR TITLE
LPS-92900 Add a param "locale" in "validateName" method to not depend on the SiteDefaultLocale

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72568. [See changes here.](https://github.com/leoadb/liferay-portal/compare/33541ba9058f~1...33541ba9058f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
