### PR TITLE
LPS-133755 parameterMap is not empty, it contains entries beside "isStagingSite"

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @leoadb 

Could you please review this pull request?

I reverted 3ab9e03 (with keeping the changes of 45ca1b5) because it failed the Poshi tests.

`_exportImportConfigurationSettingsMapFactory.buildImportPortletSettingsMap()` should get the entire `actionRequest.getParameterMap()` because it contains necessary information for the import.

Thank you and best regards,
István

### CODE REVIEW

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
@IstvanD I'm sorry for my mistake. Thanks!

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/885

**Comment by IstvanD** [comment]
Hi @leoadb no problem. Thanks for forwarding!

**Pull request closed without merging**
