### PR TITLE
LPS-79215 Analytics' fails should not break the DDMFormInstanceRecordVersion creation

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:test

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/412. [See changes here.](https://github.com/leoadb/liferay-portal/compare/6c63b9b0e23a~1...6c63b9b0e23a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/475. [See changes here.](https://github.com/leoadb/liferay-portal/compare/7be1badf0ad5~1...7be1badf0ad5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
