### PR TITLE
[TECHNICAL SUPPORT] LPS-105077 Fix unit test

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-105077

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/81475

**Pull request closed without merging**
