### PR TITLE
Revert "LRQA-34760 Quaratine forms tests until LPS-74430 and LPS-74478 are fixed"

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 Tentative to fix the issue that is prohibiting to save a form

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
@leoadb Nice!!

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 Passed right?

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:stop

**Pull request closed without merging**
