### PR TITLE
LPS-50660 - Update DDMStructure and LocalizedValues of DDMForm

### PR DESCRIPTION
**Pull request by marcellustavares**
@leoadb we need to add tests for this before fwd Linos' PR. @linolaoj do we have tests already for this? Can you send to Leo if we don't?

Thanks

### CODE REVIEW

**Comment by linolaoj** [comment]
Hi @marcellustavares  @leoadb , the current test does not cover multiples locales. I will send to Leo the test for this.

Thanks

**Comment by leoadb** [comment]
@linolaoj I'll send to you and you send me back after adding some tests

**Comment by leoadb** [comment]
Pull request forwarded to https://github.com/linolaoj/liferay-portal/pull/4. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
