### PR TITLE
LPS-101288 add and update test

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/550. [See changes here.](https://github.com/leoadb/liferay-portal/compare/1ca7f7c5077c~1...1ca7f7c5077c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
