### PR TITLE
[TECHNICAL SUPPORT] LPS-117841 Pre-defined values in Web Content structure are not displayed properly

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-117841](https://issues.liferay.com/browse/LPS-117841)

Please review my changes,

Thanks

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
ci:forward

**Comment by leoadb** [comment]
Pull request forwarded to https://github.com/jeyvison/liferay-portal/pull/797. [See changes here.](https://github.com/leoadb/liferay-portal/compare/55dcf1ef00c9~1...55dcf1ef00c9)

**Pull request closed without merging**
