### PR TITLE
LPS-102931 adding default locale

### PR DESCRIPTION
**Pull request by linolaoj**
https://issues.liferay.com/browse/LPS-102931
cc: @natocesarrego, @inacionery

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79492. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
