### PR TITLE
LPS-99541

### PR DESCRIPTION
**Pull request by jonathanmccann**
@leoadb As discussed, removed the failing test as it is covered by the integration test. Please let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77981. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
