### PR TITLE
LPS-69108 Add the configKey so the ConfigContributors can apply to this editor as well

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @leoadb 
Can you please review my changes and if they look good send the pull to Brian?
Thx!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @marcellustavares

**Comment by leoadb** [comment]
@sergiogonzalez Sure !!! Thanks a lot !!!

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44738. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
