### PR TITLE
LPS-95211 Remove localizable condition from field value access

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73545. [See changes here.](https://github.com/leoadb/liferay-portal/compare/cc4eab5684af~1...cc4eab5684af) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
