### PR TITLE
LPS-103418 reverting LPS-97757 since it is not needed anymore

### PR DESCRIPTION
**Pull request by linolaoj**
Hi, 
I'm reverting 105dd6fc109f6fb9f57125759ecfa2d37481f291,  because I could not reproduce LPS-97757 anymore and it is causing LPS-103418.

https://issues.liferay.com/browse/LPS-103418
https://issues.liferay.com/browse/LPS-97757

Thanks!

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/79983

**Pull request closed without merging**
