### PR TITLE
LPS-95698 disable user input until form is fully rendered

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73526. [See changes here.](https://github.com/leoadb/liferay-portal/compare/55b59252cef0~1...55b59252cef0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
