### PR TITLE
LPS-76385 incrementing count when captcha text is wrong

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:retest

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Looks good to me. Forwarded to Pei Jung at https://github.com/pei-jung/liferay-portal/pull/243

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
