### PR TITLE
LPS-87482 form from staging group should be visable only on staging group

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @jeyvison

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/431. [See changes here.](https://github.com/leoadb/liferay-portal/compare/9257d97ec01c~1...9257d97ec01c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65459. [See changes here.](https://github.com/leoadb/liferay-portal/compare/9257d97ec01c~1...9257d97ec01c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
