### PR TITLE
LPS-74405 Liferay Forms radio button options don't submit properly on IE11

### PR DESCRIPTION
**Pull request by natocesarrego**
Hey @leoadb,

This pull fixes an issue specific to IE 11 and apparently a work around is necessary to overcome this problem. More details can be found in this [comment](https://github.com/natocesarrego/liferay-portal/pull/91#issuecomment-325726641).

Thanks.

@IstvanD @gregory-bretall

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @leoadb,

Any update on this pull?

Thanks.

**Comment by leoadb** [comment]
@natocesarrego It's on my review queue. I'm doing other reviews before get to this. Thanks!

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51358. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
