### PR TITLE
LPS-74838 Problem: "The selected form no longer exists" when submitting a Webform to a configured URL

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @leoadb 

Could you please check this pull request?

Explanation of the solution:

If a `redirectURL` is set for the Form, `AddRecordMVCActionCommand.doProcessAction()` will be called twice, but on the second invocation, the `groupId` and `recordSetId` request params won't be available, therefore, we have so save it between the calls.

Thank you and best regards,
István

### CODE REVIEW

**Comment by janditibi** [comment]
ci:reopen

**Comment by janditibi** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Changes already merged by BChan https://github.com/brianchandotcom/liferay-portal/pull/53036.

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
