### PR TITLE
Lps 102715 katie

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @katienesterovich

Notes from Katie:
> **Ticket**: https://issues.liferay.com/browse/LPS-102715
> 
> **Reason**: Purposeful removal of FontAwesome and Glyphicons https://issues.liferay.com/browse/LPS-95502
> 
> **Fix**: mimics https://github.com/brianchandotcom/liferay-portal/pull/76557/files from https://issues.liferay.com/browse/LPS-99145

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/79403

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
