### PR TITLE
[TECHNICAL SUPPORT] LPS-105077 Introducing translated months and weekdaysShort to Date Field's template context

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-105077

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/rodrigopaulino/liferay-portal/pull/23

**Pull request closed without merging**
