### PR TITLE
[TECHNICAL SUPPORT] LPS-117016 Apply the number format treatment on unlocalized fields too

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-117016

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/leoadb/liferay-portal/pull/957

**Pull request closed without merging**
