### PR TITLE
LPS-67815 When update ddmcontent, we should use completed fields (including parentStructure fields) to update.

### PR DESCRIPTION
**Pull request by marcellustavares**
@leoadb could you please add integration tests for this? Thanks

### CODE REVIEW

**Comment by daledotshan** [comment]
@leoadb 
Could you help to review this pull request as high priority as we have a ee customer is waiting for this fix?
Thanks,
Dale

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
@marcellustavares Should I send back to you or I can forward to BChan when I'm done ?

**Comment by marcellustavares** [comment]
@leoadb, just cc me on the final pull.

Also, please rename the method from `getFullDDMForm` to `getFullHierarchyDDMForm` to mach with DDMStructure method.

Thanks

**Comment by leoadb** [comment]
@marcellustavares ok Thanks !!!

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43088. [See changes here.](https://github.com/leoadb/liferay-portal/compare/9c148f0~2...9c148f0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
