### PR TITLE
LPS-56946 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
@leoadb, could you help me out to test Adolfo's fix?

Thanks

### CODE REVIEW

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
@marcellustavares, it's working. @adolfopa thanks !!!

**Comment by marcellustavares** [comment]
@leoadb, could you send to Brian?

Thx

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28085. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
