### PR TITLE
LPS-93142 Add random data definition with field and validation.

### PR DESCRIPTION
**Pull request by mclomello**
Leo, could u review this pr please?

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73451. [See changes here.](https://github.com/leoadb/liferay-portal/compare/2c4a2802b005~2...2c4a2802b005) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
