### PR TITLE
LPS-101196 Repeated Fields are initially empty and should be populated with default data

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:test:sf

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@leoadb probably unrelated, looks like portal got stuck during the test, and the other two upgrade test batches passed.

**Comment by leoadb** [comment]
@jpince Thanks!

**Comment by leoadb** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/78232

**Pull request closed without merging**
