### PR TITLE
LPS-75285 Auto SF

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:reopen

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52365. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
