### PR TITLE
LPS-50660

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@leoadb see https://github.com/brianchandotcom/liferay-portal/pull/30993

Can you sort

		predefinedValue.addString(LocaleUtil.US, "Test1 us");
		predefinedValue.addString(LocaleUtil.BRAZIL, "Test1 br");
		predefinedValue.addString(LocaleUtil.ITALY, "Test1 es");
		predefinedValue.addString(LocaleUtil.FRENCH, "Test1 fr");

		Set<Locale> availableLocales = DDMFormTestUtil.createAvailableLocales(
					LocaleUtil.US, LocaleUtil.BRAZIL, LocaleUtil.ITALY,
					LocaleUtil.FRENCH);

Why are we doing "es" for Italian? That's for Spanish?

Also, is Marcellus back from Devcon, if so, can you start sending these to him? Thx.

**Comment by leoadb** [comment]
@brianchandotcom l'll fix and rebase as you asked. Marcellus is on vacation until the end of this month.

**Comment by leoadb** [comment]
@brianchandotcom sorry for miss that.

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brandizzi/liferay-portal/pull/77. [See changes here.](https://github.com/leoadb/liferay-portal/compare/c22031d~1...c22031d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
