### PR TITLE
[TECHNICAL SUPPORT] LPS-102042 Remove values from invisible fields

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-102042

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
Hey, @leoadb. Do you have any updates on this review?

Best.

**Comment by inacionery** [comment]
Hey @rodrigopaulino,

Leonardo is in PTO, I'll take care of it, is already in my queue.

Regards.

**Comment by rodrigopaulino** [comment]
Thanks, @inacionery.

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79039

**Comment by inacionery** [comment]
ci:close

**Pull request closed without merging**
