### PR TITLE
LPS-62945 Form Workflow - A deleted entry is not removed from My Workflow Tasks or My Submissions portlet

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35975. [See changes here.](https://github.com/leoadb/liferay-portal/compare/b4f21b7~1...b4f21b7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
There are test failures in this pull @leoadb, I guess it will break in Brian :)

**Comment by leoadb** [comment]
@marcellustavares thanks !!! I just closed it. I'll take a look and probably send to @victorware to fix the Poshi tests.

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/179. [See changes here.](https://github.com/leoadb/liferay-portal/compare/53a15de~1...53a15de) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36079. [See changes here.](https://github.com/leoadb/liferay-portal/compare/0398bc0~2...0398bc0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
