### PR TITLE
LPS-96234 SF

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74177. [See changes here.](https://github.com/leoadb/liferay-portal/compare/093c3bef65f5~1...093c3bef65f5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/473. [See changes here.](https://github.com/leoadb/liferay-portal/compare/6fee26bc4b2b~1...6fee26bc4b2b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/417. [See changes here.](https://github.com/leoadb/liferay-portal/compare/6fee26bc4b2b~1...6fee26bc4b2b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/474. [See changes here.](https://github.com/leoadb/liferay-portal/compare/63cc50cd5431~1...63cc50cd5431) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
