### PR TITLE
LRQA-32676 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Hey @leoadb, Subrepo merge completed.

I added the tests back in on top of this pull, but now I have a rebase error. I was not sure how to solve it myself. We are so close.

### CODE REVIEW

**Comment by vicnate5** [comment]
Rebase error:

`modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/main/resources/META-INF
/resources/admin/js/form_portlet.js`
```
<<<<<<< HEAD
						if (value) {
							A.one('.publish-icon')
								.removeClass("disabled")
								.attr('title', Liferay.Language.get('copy-url'));
						}
						else {
							A.one('.publish-icon')
								.addClass("disabled")
								.attr('title', Liferay.Language.get('publish-the-form-to-get-its-shareable-link'));
						}
=======
						var publishIcon = A.one('.publish-icon');

						publishIcon.toggleClass('disabled', !value);
>>>>>>> LPS-71378 Adds support for translating form
```

**Comment by vicnate5** [comment]
@marcellustavares

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/leoadb/liferay-portal/pull/338. [See changes here.](https://github.com/leoadb/liferay-portal/compare/b5f05ee~1...b5f05ee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49089. [See changes here.](https://github.com/leoadb/liferay-portal/compare/b5f05ee~1...b5f05ee) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49103. [See changes here.](https://github.com/leoadb/liferay-portal/compare/747d40d~1...747d40d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49116. [See changes here.](https://github.com/leoadb/liferay-portal/compare/189b661~2...189b661) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49119. [See changes here.](https://github.com/leoadb/liferay-portal/compare/5f4285e~2...5f4285e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49120. [See changes here.](https://github.com/leoadb/liferay-portal/compare/61d95b4~2...61d95b4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49122. [See changes here.](https://github.com/leoadb/liferay-portal/compare/946dd0c~3...946dd0c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
