### PR TITLE
LPS-108891 Check structure field for null before adding it

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
@leoadb discussed with @jeyvison and @gabrielwas and this seems to be the easiest fix, although we know the correct fix is to work with structure versions, this will require many changes and we don't want to do it now.

**Comment by brunofarache** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/85522

**Pull request closed without merging**
