### PR TITLE
LPS-104964 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @leoadb,
 did you have time to take a look to the current pull?
Kind regards.

/cc @jeyvison

**Comment by leoadb** [comment]
@marianoalvarosaiz waiting for one change I sent on other pull to get merged because I've updated dynamic-data-mapping-api version

**Comment by leoadb** [comment]
Just started reviewing :)

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/83836

**Comment by leoadb** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/83836

**Pull request closed without merging**
