### PR TITLE
Revert "LRQA-34760 Quaratine forms tests until LPS-74430 and LPS-74478 are fixed"

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 Trying to fix the save issue

**Comment by vicnate5** [comment]
@leoadb You don't need to use 3572be39e8ab46aa932aa974953fd63024c0a983 anymore

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
Forgot to rebase with master :(

**Pull request closed without merging**
